import java.util.Date
import java.lang.*;

declare Address
    name : String
end

declare Person
    name : String
    dateOfBirth : Date
    address : Address
end

rule "Using a declared Type Mark"
when
    $p : Person( name == "Bob" )
then
    // Insert Mark, who is Bob's mate.
    Person mark = new Person();
    mark.setName("Mark");
    insert( mark );
    Thread.sleep(1000);
end

rule "Using a declared Type 2"
no-loop true
when
    p : Person( name == "Mark" )
then
    // Insert Mark, who is Bob's mate.
    Address myadd = new Address();
    myadd.setName("Poudlard");
    modify( p ) {setAddress( myadd )}
    Thread.sleep(1000);
end