declare POS
    office: String
end

declare POSMatch
    id: String
end

rule "POS1"
when
    $p : POS( office== "NCE1A0ABR" )
then
    // Insert Mark, who is Bob's mate.
    POSMatch pos = new POSMatch();
    pos.setId("POS1");
    insert( pos);
    Thread.sleep(1000);
end

rule "POS2"
when
    $p : POS( office== "NCE1A0950" )
then
    // Insert Mark, who is Bob's mate.
    POSMatch pos = new POSMatch();
    pos.setId("POS2");
    insert( pos);
    Thread.sleep(1000);
end

rule "Rule 1"
when
    POSMatch( id== "POS1" )
    POSMatch( id== "POS2" )
then
    Thread.sleep(1000);
end